name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy
        id: deploy
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys)

          echo "RESPONSE=$RESPONSE"
          DEPLOY_ID=$(echo $RESPONSE | jq -r '.id')
          echo "DEPLOY_ID=$DEPLOY_ID"
          echo "deploy_id=$DEPLOY_ID" >> $GITHUB_OUTPUT

      - name: Wait for Render deploy to finish
        run: |
          echo "Waiting for Render deploy to complete..."
          DEPLOY_ID=${{ steps.deploy.outputs.deploy_id }}

          for i in {1..60}; do
            STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              https://api.render.com/v1/deploys/$DEPLOY_ID | jq -r '.status')

            echo "Deploy status: $STATUS"

            if [[ "$STATUS" == "live" ]]; then
              echo "✅ Deploy successful!"
              exit 0
            elif [[ "$STATUS" == "build_failed" || "$STATUS" == "failed" ]]; then
              echo "❌ Deploy failed!"
              exit 1
            fi

            sleep 10
          done

          echo "❌ Timeout: Deploy took too long."
          exit 1
